name: 'amir_tourist_service'

services:
  gateway:
    build: ./gateway
    ports:
      - '9088:9088'
    restart: always
    volumes:
      - './gateway/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
    depends_on:
      - frontend
      - backend
    networks:
      network:
        ipv4_address: 22.98.1.22

  postgres:
    image: postgres
    ports:
      - '5432:5432'
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=voyage-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=egor_letow
      - MAX_LOGIN_ATTEMPTS=0
    networks:
      network:
        ipv4_address: 22.98.1.4

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - 4590:4590
    depends_on:
      - postgres
    networks:
      network:
        ipv4_address: 22.98.1.57

  frontend:
    build: ./frontend
    ports:
      - '8014:5523'
    restart: always
    environment:
      - VITE_API_URL=http://87.242.117.193:9088/api
    depends_on:
      - backend
    volumes:
      - './frontend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
    networks:
      network:
        ipv4_address: 22.98.1.64

volumes:
  postgres-data:
  pgadmin:

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 22.98.0.0/16
          gateway: 22.98.0.1
