on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: connect and pull
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
          "cd ${{ secrets.WORK_DIR }} && \
          git checkout ${{ secrets.MAIN_BRANCH }} && \
          git pull"

  build_containers:
    needs: run_pull
    runs-on: ubuntu-latest
    steps:
      - name: building docker images
        run: |
          cd ./docker \
          && sudo docker compose \
          -f docker-compose.prod.yml \
          -p prod \
          up -d --build

  clean_up:
    needs: run_pull
    runs-on: ubuntu-latest
    steps:
      - name: clean up
        run: rm -rf ~/.ssh
